name: SmallRye Build

on:
  push:
    branches:
      - main
      - 3.1.x
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17-ea' ]
    name: Build with JDK ${{matrix.java}}

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Build with Maven
        run: mvn -B javadoc:javadoc formatter:validate verify
      - uses: actions/upload-artifact@v2
        name: TCK report
        with:
          name: tck-report
          path: testsuite/tck/target/surefire-reports

  quality:
    needs: [build]
    if: github.event_name == 'push' && github.repository == 'smallrye/smallrye-health'
    runs-on: ubuntu-latest
    name: quality

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: sonar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -B verify --file pom.xml -Pcoverage javadoc:javadoc sonar:sonar -Dsonar.organization=smallrye -Dsonar.projectKey=smallrye_smallrye-health -Dsonar.login=$SONAR_TOKEN -Dmaven.test.failure.ignore=true
