name: SmallRye Pre Release

on:
  pull_request:
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: pre release

    steps:
      - uses: radcortez/project-metadata-action@main
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - name: Validate version
        if: contains(steps.metadata.outputs.current-version, 'SNAPSHOT')
        run: |
          echo '::error::Cannot release a SNAPSHOT version.'
          exit 1

      - uses: radcortez/milestone-review-action@main
        name: milestone review
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          milestone-title: ${{steps.metadata.outputs.current-version}}

  integration-verification:
    runs-on: ubuntu-latest
    name: Integration verification
    if: contains(github.event.pull_request.body, 'Breaking change') == false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn -B javadoc:javadoc formatter:validate install

      - id: version-step
        name: Save version for integration builds
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "::set-output name=SNAPSHOT_VERSION::$VERSION"

      - uses: actions/checkout@v2
        name: Checkout Quarkus
        with:
          repository: quarkusio/quarkus

      - name: Quarkus integration
        run: |
          mvn -Dquickly -Dsmallrye-health.version=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
          mvn clean verify -pl extensions/smallrye-health/deployment -Dsmallrye-health.version=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
          mvn clean verify -pl tcks/microprofile-health -Dtcks -Dsmallrye-health.version=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}

      - uses: actions/checkout@v2
        name: Checkout WildFly
        with:
          repository: wildfly/wildfly

      - name: WildFly integration
        run: |
          mvn clean install -DskipTests -DskipITs -Denforcer.skip -Dversion.io.smallrye.smallrye-health=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
          mvn clean verify -pl microprofile/health-smallrye -Dversion.io.smallrye.smallrye-health=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
          mvn clean verify -pl testsuite/integration/microprofile -Dts.standalone.microprofile -Dversion.io.smallrye.smallrye-health=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
          mvn clean verify -pl testsuite/integration/microprofile-tck/health -Dts.standalone.microprofile -Dversion.io.smallrye.smallrye-health=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
          mvn clean verify -pl testsuite/integration/manualmode -Dts.manualmode -Dtest="MicroProfile*" -Dversion.io.smallrye.smallrye-health=${{ steps.version-step.outputs.SNAPSHOT_VERSION }}



          
          
